### ISSUE TITLE
Umlaute werden im Titel veschluckt...

### ISSUE THREAD

**Issue by Perun** [bueltge/AddQuicktag#32]
Hallo Frank,
wenn ich AddQuickatgs in WordPress ohne die deutsche Sprachdatei nutze und einen Button mit Umlauten beschrifte, dann werden die Umlaute "verschluckt": aus ü wird u.

**Comment by bueltge** [comment]
@Perun  Danke nochmal!. Fix kommt gleich in die neue Version.
