### ISSUE TITLE
WP 4.9.8 and Gutenberg as plugin

### ISSUE THREAD

**Issue by bueltge** [bueltge/AddQuicktag#45]
if we would use the plugin also with the Gutenberg editor, we need a enhancement.

### Ressource

 * https://github.com/inpsyde/gutenberg-example
 * https://github.com/zgordon/gutenberg-course
 * https://www.billerickson.net/building-gutenberg-block/
 * https://github.com/WordPress/gutenberg-examples
 * https://github.com/ahmadawais/create-guten-block
 * https://github.com/ahmadawais/Gutenberg-Boilerplate
 * https://github.com/cedaro/wp-address-block
 * https://github.com/georgestephanis/GS-Gutenblocks
 * https://github.com/lucasstark/gutenberg-gravityforms
 * https://deliciousbrains.com/custom-gutenberg-block/

**Comment by studioart** [comment]
Issue with the Gutenberg plugin and WP 4.9.8.
The activation of AddQuicktag is without any error messages, but as soon as we open a page/post or editing, then on top of it appears an error:

`Warning:  count(): Parameter must be an array or an object that implements Countable in xxxxxxxx/wp-content/plugins/addquicktag/addquicktag.php on line 230`

**Comment by bueltge** [comment]
@studioart Thanks for the hint. Please can you download the current master and test it, should be fixed for now. Thanks for your feedback of the test so that I can release a new version.

**Comment by studioart** [comment]
thanks, I tried it with the new version, and now I got this message in backend when editing a page:

```
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>xxxxxxxxxx/wp-content/plugins/AddQuicktag/addquicktag.php</b> on line <b>228</b><br />
		<script type="text/javascript">
			var addquicktag_tags = {"buttons":""},
				addquicktag_post_type = "page",
				addquicktag_pt_for_js = ["post","page","attachment","wp_block","comment","edit-comments","widgets"];
		</script>
```

**Comment by bueltge** [comment]
Thanks @studioart 
Please try again, a overwrite of the file `plugins/AddQuicktag/addquicktag.php` is sufficient. Thanks again!

**Comment by studioart** [comment]
Thanks a lot, the error messages are now gone. But where are now the "Quicktags" in a Gutenberg page located?
http://imgbox.com/TaPegufd

I have imported a lot from my "normal" WP (without Gutenberg plugin), they are all there at AddQuicktags -> Settings: http://imgbox.com/cL1Wpp7z

But they don't appear at a page edited with Gutenberg (plugin).

**Comment by bueltge** [comment]
The plugin don't work on the Gutenberg Editor, only on Classic editor. Currently we haven't support for Gutenberg. However currently we haven't requirements from users for implement support for Gutenberg.

![image](https://user-images.githubusercontent.com/133425/48094127-9fe97a00-e211-11e8-990b-7131b00d45f5.png)

**Comment by studioart** [comment]
Thanks, okay. As said in the forum we have tons of Quicktags like own shortcodes or other theme specific parts of texts, inline CSS/HTML things etc. - very individual things. It would be very sad, if we cannot use all these benefits in Gutenberg UI

**Comment by bueltge** [comment]
However you can use reusable blocks inside Gutenberg. Maybe this helps you to use your custom input on Quicktags?

**Comment by bueltge** [comment]
@studioart I will close this issue, your topic should be fixed. However I have a first try for an enhancement for Gutenberg in the branch [gutenberg](https://github.com/bueltge/AddQuicktag/tree/gutenberg), maybe you will try it - please not, is only a test, currently with a static tag value, a new filter is necessary. 

![image](https://user-images.githubusercontent.com/133425/48715110-89312300-ec14-11e8-8347-9660e086d783.png)


The Gutenberg enhancement should we discuss in #46
