### ISSUE TITLE
AddQuicktag Dropdown not visible Classic Editor

### ISSUE THREAD

**Issue by cargeo** [bueltge/addquicktag#49]
Similiar to the problem in 5.6 ([issue here](https://github.com/bueltge/addquicktag/issues/48)), the AddQuicktag Dropdown is not visible in Classic Editor (WP 5.7) 

The strange behaviour: In Gutenberg it is visible when adding a new Classic Editor block. But after saving the post, the same block has suddenly no more AddQicktag dropdown. See demo:

![7sjIRo88g2](https://user-images.githubusercontent.com/14090070/110608863-ec9c4180-818c-11eb-962b-a885a23070c8.gif)

When working with the Plugin „Classic Editor“ enabled, the AddQuicktag dropdown never - or very rarely - shows up. 

No errors in console.

Tried it on a fresh **WP 5.7** install, Chrome and Firefox, latest. Mac OS X.

Besides: The dashicon selection on the settings page doesn't work.

**Comment by bueltge** [comment]
I mean is a problem with the core update from WordPress with a newer jQuery Version. I will work on this. Sorry for waiting, but free time for this project is rare. same like ise #48

**Comment by bueltge** [comment]
@cargeo Please look at my feedback on issue #48 Thanks.
