### ISSUE TITLE
Custom Tags Disappear

### ISSUE THREAD

**Issue by MikePear** [bueltge/addquicktag#50]
I tried to create a new custom tag. All of my custom tags disappeared from the text edit screen. The new one did not register. They still existed but had become unchecked. Checking them and saving did not restore them.

I exported to json file, then uninstalled and reinstalled. Then tried to import the json file. The program indicated that the json file was imported, but the custom tags were all gone.

**Comment by bueltge** [comment]
The new version 2.6.1 should fix them.
